### ISSUE TITLE
Coaches Registration Form 

### ISSUE THREAD

**Issue by ferbsx** [rubymonsters/rgbapp#110]
Hi,
I would really like if we could also have the coaches registration form on this app. So if your bored with all the attendee forms you could do this, but the priority is definitely to the attendee forms (as they are way more complicated with the "confirmation" and the whole accepted/ wait-listed/ rejected concept).
This is how the current form looks like.
I would also like the added checkbox of 
- I identify as female.
If you'd like you can have it as a Gender : M / S type of a thing or whatever you like.

Plain text:
Beginners Workshop July 20th & 21st
Dear Rails Girls Berlin coaches,
we are looking for helping hands for our next beginners workshop.

When:
Installation Get-Together 20.07. 18:15 - 20:30
Workshop Day 21.07. 10:00 - 18:00

Where: 
Installation Get-Together: Posteo, Methfesselstraße 32, 10965 Berlin
Workshop Day: Le Wagon, Rudi-Dutschke-Straße 26, 10969 Berlin

Schedule & Details: http://wp.me/P4oXTv-IQ

* Required
Your Name *
Your answer
E-Mail *
Your answer
Preferred Language *
German
English
I am a first time coach
Yes
No
I can help *
on the installation party
on the workshop day
on both days
Would you like to give a Ligthning Talk? What topic do you have in mind?
The talk should be understanable for beginners and not longer than 5 minutes.
Your answer

Notes (including if you would like to help the organisers on the day or even become an organiser in the future)
Your answer

Please read and accept our Code of Conduct http://berlincodeofconduct.org/de/ *
"I have read the code of conduct and comply to it"
SUBMIT

Screen shots:
![screen shot 2018-08-27 at 8 40 33 pm](https://user-images.githubusercontent.com/11502220/44678809-88378d80-aa39-11e8-9786-246433f0e644.png)
![screen shot 2018-08-27 at 8 40 41 pm](https://user-images.githubusercontent.com/11502220/44678810-88378d80-aa39-11e8-97ef-68f131904847.png)
![screen shot 2018-08-27 at 8 40 48 pm](https://user-images.githubusercontent.com/11502220/44678811-88d02400-aa39-11e8-9443-3094852365a7.png)

**Comment by ferbsx** [comment]
When the form is not accepting any more applications (after the coaches application deadline - this is different to the attendee deadline, we usually give coaches a few more days to sign up), this pops up if they try to register:

> You can no longer register to coach at the Rails Girls Berlin (code curious) Beginners Workshop, as the registration deadline has passed.
>
> Try contacting the Rails Girls Berlin (code curious) organisers, if you think that this is a mistake at contact@railsgirlsberlin.de

**Comment by ferbsx** [comment]
After they have filled up the form, this shows up:
>Thank you for registering. You will get detailed information in the week before the workshop. :)
> If you have any questions, don't hesitate to write us at <coaching@railsgirlsberlin.de>.
>
>    Rails Girls Berlin (code curious) Team

**Comment by agatakrawczyk** [comment]
Ferdous i'll write here your workflow you sent me, to keep it in one place:

"Another thing to keep in mind with coaches is that, there are a few black listed coaches." 

WORKFLOW:
- adjust the Google form by writing the correct dates and stuff
- open application
- every few days, I check in to see how many coaches have applied (it would be super awesome if the app could maybe send me an email every other day, letting me know how many coaches applied) > this affects our twitting and emailing and reaching out to coaches 
- the coaches registration usually doesn't have the same deadline as the attendees application. So if we have enough coaches by that deadline, I close it, if not, it stays open till we do/ the day before the workshop (oftentimes, coaches register last minute because they're not sure if they're free on that weekend and we don't want to reject them since we still need them)
- a week before the workshop, I check the coaches, if any is black-listed, I write them a polite email explaining why we would not like to have their help
- I remove duplicates (coaches often forget if they have already applied :sweat_smile: )
- I also send the coaches-info email telling them all about the run-down, the schedules, tutorials, who does a lightning talk, etc. (This is in the email in the issue on GitHub)
- then some coaches cancel, because they forgot they had applied, or they're sick now or for whatever reason
- so I remove them and make new plans 
- in the mean time, more coaches might've registered, so I send them the coaches-info mail"

**Comment by simaofreitas** [comment]
@ferbsx 

> a week before the workshop, I check the coaches, if any is black-listed, I write them a polite email explaining why we would not like to have their help

Is this email the same for every blacklisted person? Should we define it as an email template for the event?

**Comment by simaofreitas** [comment]
Todo:

 - [ ] Improve error message when no longer possible to apply to coach an event
 - [ ] Improve success message after successful application as coach for event
 - [ ] Add privacy notice to coach application form
 - [ ] Add boolean columns for lightning talk (morning/afternoon)
 - [ ] approval for coaches
 - [ ] approval for lighting talks
 - [ ] Add email for coaches confirmation
 - [ ] Add field to mark if email was sent to coach already
 - [ ] Add cancel button for coach application

**Comment by juopmu** [comment]
We finished the basic implementation and moved the remaining improvements to a new issue #214

**Comment by ferbsx** [comment]
> @ferbsx
> 
> > a week before the workshop, I check the coaches, if any is black-listed, I write them a polite email explaining why we would not like to have their help
> 
> Is this email the same for every blacklisted person? Should we define it as an email template for the event?

No the email isn't always the same. But it would be cool to still have a template (in which I would most probably write some example responses and general tips on how to formulate the email). It's tricky to write these emails since we don't want to hurt anyone but also want to keep a safe space and have coaches we can rely on.

I'm sorry for not answering here earlier, I just saw the question now after I got the email that the issue was closed. Maybe it still helps (@juopmu )
