### ISSUE TITLE
Coach registration improvements

### ISSUE THREAD

**Issue by juopmu** [rubymonsters/rgbapp#214]
- [x] approval for coaches
 - [x] approval for lighting talks
 - [x] Add email for coaches confirmation
 - [x] Add field to mark if email was sent to coach already
 - [x] Add cancel button for coach application

**Comment by ferbsx** [comment]
There are lightning talks after lunch (so around 1 pm, we usually around 2-4 of them, each around 5-10 mins). We strive to always have at least one inspirational talk from a former Rails Girls Berlin/ code curious attendee telling their success story.

We also have `one` talk which is the "how to continue learning" talk at he end of the workshop day. (So maybe this could be a boolean of "do you want to give the how to continue learning" talk?". We have slides for it, but also welcome coaches who want to make their own slides for it.)

Just wanted to clarify this since I saw the `(morning/afternoon)` part of the task.
