### ISSUE TITLE
Add explanations and better labels to the form

### ISSUE THREAD

**Issue by porras** [rubymonsters/rgbapp#5]
It's currently not clear about what it's about, and what's expected to be filled in the non obvious fields (other than name and email).

**Comment by ferbsx** [comment]
# Rails Girls Berlin Beginners Workshop <date, eg: 25.3.2017>
Rails Girls Berlin want to give total beginners the opportunity and a community to start learning the technology to build their ideas and continue coding.
The Beginners Workshop is a hands on introduction to Rails. The workshop has a main focus on women with no previous Ruby on Rails programming experience and who want to be able to build their own applications. The program of the workshop includes an overview of the Rails framework and a practical exercise in which attendees will be guided by coaches through the application building process.

We provide a completely differently learning environment in order to not only support but also further motivate women who want to code, but don’t have the right environment to do so. We also aim to establish a community, so it’s not a once in a life-time event, we want to help women code and encourage them to continue coding.

No previous knowledge is required to attend this workshop.

The first steps of learning how to program can be difficult. Our goal is it to help you with these first steps. We want to show you that programming is fun and creative and that there is a wonderful community that will support you.

We are looking forward to see you <3

Application Start: \<date>
Application End: \<date>
Confirmation Mails: \<date>

\* Required
- **First Name** (No official name necessary, you can use the name you want to be called.) *
Vorname (Muss kein offizieller Name sein - wähle den, mit dem du genannt werden möchtest.)
\<Your answer>

- **Surname** *
Nachname
\<Your answer>

- **E-Mail Address** *
\<Your answer>

- **Do you want to learn in English or German?** *
English
German
Both are fine for me

- **Have you attended a Rails Girls Berlin Workshop before?** *
Never
I've not been to a Rails Girls Berlin Workshop, but I have been to a Rails Girls Workshop before
Yes

- **What level of coding do you see yourself in Rails?** (0=never coded before; 10=expert) *
0
1
2
3
4
5
6
7
8
9
10

- **What operating system do you have?** *
Windows
Mac OS X 10.6 and later
Mac OS X 10.5 or earlier
Linux
Other: \<text>

- **Can you programm in another programming language?** If so, which language(s) and at what level (0=never coded before; 10=expert) *
\<Your answer>

- **Have you tried any Rails tutorials already?** If so which ones? Did you have any difficulties? *
\<Your answer> 

- **Please read and accept our Code of Conduct** http://berlincodeofconduct.org/de/ *
"i have read the code of conduct and comply to it"

- **Is there anything else that you would like to mention?**
\<Your answer>

SUBMIT
![screen shot 2017-03-14 at 10 47 03 am](https://cloud.githubusercontent.com/assets/11502220/23894804/d02a59b2-08a3-11e7-83af-b26c390bd5b9.png)
![screen shot 2017-03-14 at 10 47 12 am](https://cloud.githubusercontent.com/assets/11502220/23894806/d096400a-08a3-11e7-99e2-efa319310f68.png)
![screen shot 2017-03-14 at 10 47 22 am](https://cloud.githubusercontent.com/assets/11502220/23894803/cfc81270-08a3-11e7-9d91-692474ecbc3e.png)
![screen shot 2017-03-14 at 10 47 28 am](https://cloud.githubusercontent.com/assets/11502220/23894802/cfabb918-08a3-11e7-91a4-f3c26f8a5c3d.png)

**Comment by ferbsx** [comment]
This is the form as it is now. 
We don't have the "female*?" question and we ask for name and surname separately. We'll talk about the exact wording of them tonight at the organisers meeting and I'll get back to you 😃

**Comment by ferbsx** [comment]
As a result of the orga meeting regarding 👆 , please use the following wording:
- Full name (No official name necessary, you can use the name you want to be called. Just be sure to remember it.) \<text>
- \<checkbox> I am a woman / non-binary person.

although we still have to review the wording for the latter question, we are going to consult more people and get back to you. But this wording should be fine as a place-holder for now :)

I hope all of this is enough for now. If you need anything else, don't hesitate to ping me. We're really happy that you all are doing this. ❤️

**Comment by porras** [comment]
Some things we have done a bit differently, we should check that they are ok or create issues to fix them later:

* In the language we don't have a _both_ option, but they are checkboxes (and one can mark both)
* In the previous attendance question, there is only yes and no
* The OS dropdown only has one Mac option (instead of two, older and newer)

/cc @ferbsx @Powerglove
